/**
 * Print-friendly case report. The user (or the SignoffExports component)
 * navigates here in a new window, the page auto-prints, and the browser's
 * print dialog produces the PDF.
 *
 * Layout is intentionally bare — paper-white background, serif type, no
 * sidebar/topbar chrome — so the resulting PDF reads like a forensic
 * journal article, not a screenshot of the app.
 */

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { findPeer } from "@/lib/peers";
import { getSignoff } from "@/lib/signoffs";
import { severityLabel } from "@/lib/triage";
import { PrintAutorun } from "./PrintAutorun";
import { ReportMarkdown } from "./ReportMarkdown";

export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  return { title: `Case report · ${id}` };
}

export default async function PrintPage({
  params,
  searchParams,
}: {
  params: Promise<{ id: string }>;
  searchParams: Promise<{ auto?: string }>;
}) {
  const { id } = await params;
  const sp = await searchParams;
  const record = await getSignoff(id);
  if (!record) notFound();

  const verdict = record.results?.verdict as
    | { headline?: string; overallSeverity?: number; failurePointTurn?: number | null }
    | undefined;
  const filer = record.filedBy ? findPeer(record.filedBy) : null;
  const reviewer = findPeer(record.assignedTo);
  const finalDecider = record.aiReview
    ? findPeer(record.aiReview.finalDeciderPeerId)
    : record.decidedBy
      ? findPeer(record.decidedBy)
      : null;

  return (
    <main className="print-report">
      {sp.auto === "1" && <PrintAutorun />}

      <header style={{ marginBottom: 24 }}>
        <div
          style={{
            fontFamily: "var(--font-mono)",
            fontSize: 11,
            letterSpacing: "0.16em",
            textTransform: "uppercase",
            color: "#a6324a",
            marginBottom: 6,
          }}
        >
          Primum forensic console · case report
        </div>
        <h1
          style={{
            fontFamily: "var(--font-serif)",
            fontSize: 28,
            lineHeight: 1.15,
            letterSpacing: "-0.012em",
            color: "#101015",
            margin: 0,
            fontWeight: 600,
          }}
        >
          {verdict?.headline ?? `Case ${record.id}`}
        </h1>
        <div
          style={{
            marginTop: 12,
            display: "flex",
            gap: 22,
            flexWrap: "wrap",
            fontFamily: "var(--font-mono)",
            fontSize: 11,
            color: "#3a3a45",
            letterSpacing: "0.04em",
          }}
        >
          <span>id · {record.id}</span>
          <span>filed · {new Date(record.filedAt).toISOString().slice(0, 16).replace("T", " ")}</span>
          {filer && <span>by · {filer.name}</span>}
          {reviewer && <span>assigned · {reviewer.name}</span>}
          {typeof verdict?.overallSeverity === "number" && (
            <span>
              severity · {verdict.overallSeverity} ({severityLabel(verdict.overallSeverity)})
            </span>
          )}
          {typeof verdict?.failurePointTurn === "number" && (
            <span>failure · turn {verdict.failurePointTurn}</span>
          )}
          {finalDecider && record.status !== "awaiting" && (
            <span>
              {record.status} by · {finalDecider.name}
            </span>
          )}
        </div>
      </header>

      <ReportMarkdown id={record.id} initial={record.postmortemMarkdown ?? null} />

      <footer
        style={{
          marginTop: 36,
          paddingTop: 16,
          borderTop: "1px solid #d8d4ca",
          fontFamily: "var(--font-mono)",
          fontSize: 10.5,
          color: "#7a7770",
          letterSpacing: "0.06em",
        }}
      >
        Generated by Primum · the audit pipeline at the speed of deployment.
      </footer>
    </main>
  );
}
