import { Audio, staticFile } from "remotion";

/**
 * Plays the voiceover MP3 generated by scripts/generate-voiceover.ts for
 * this segment. If the file isn't there yet (script still being drafted),
 * the component renders nothing — Remotion Studio won't error out.
 */
export const VoiceTrack: React.FC<{ id: string }> = ({ id }) => {
  const src = staticFile(`voiceover/${id}.mp3`);
  // Remotion can't easily check static-file existence at render time, so we
  // wrap in <Audio> unconditionally. Missing files yield a silent track at
  // render time (the renderer logs a warning but the build still completes).
  return <Audio src={src} volume={1} />;
};
